export const personalInfo = {
  name: "Aaron Nader",
  title: "Software Engineer",
  email: "aaron@example.com",
  birthday: "1996-04-23",
  websiteCreated: "2022-12-01",
  intro:
    "Hey there! I'm Aaron Nader. I've been working as a Software Engineer for quite a while, diving deep into both front-end and back-end development. I'm passionate about building smooth, user-friendly interfaces with React and creating solid, reliable back-end systems using Node.js. I'm all about writing clean, efficient code, whether I'm building intuitive UIs or optimizing server-side performance. I've got a full-stack background and always stay curious, eager to pick up new technologies and improve my skills along the way. When I'm not coding, you can find me staying active and focused on my fitness and mental health. I'm also the founder of Immaculate Heart Tech, where I get to combine my love for tech with my passion for creating meaningful, innovative solutions.",
  links: {
    resume: "/resume.pdf",
    linkedin: "https://www.linkedin.com/in/aaron-nader-1a6073238/",
    github: "https://github.com/AaronNader96",
    sourceCode: "https://github.com/AaronNader96/aaronnader-portfolio-v2",
  },
};

export const techStack = [
  "React JS",
  "Node JS",
  "JavaScript",
  "SQL (PostgreSQL, MSSQL, Firebase, Supabase, Teradata, Snowflake)",
  "Vite",
  "OCP Container",
  "Jenkins",
  "Git",
];

export const projects = [
  {
    id: 1,
    title: "ParishFlow",
    description: "Parish management platform for churches.",
    technologies: ["React", "Chakra UI", "JavaScript"],
    github: null,
    demo: "https://parishflow.com/",
    image: "assets/parishflow.png",
  },
  {
    id: 2,
    title: "Immaculate Heart Tech",
    description: "Company website for Immaculate Heart Tech.",
    technologies: ["React", "Chakra UI", "JavaScript"],
    github: null,
    demo: "https://immaculateheart.tech/",
    image: "assets/iht.png",
  },
  {
    id: 3,
    title: "Be A Light Photography",
    description: "Portfolio site for Be A Light Photography.",
    technologies: ["React JavaScript", "Chakra UI", "Vite"],
    github: null,
    demo: "https://bealightphotography.com/",
    image: "assets/bealight.png",
  },
  {
    id: 4,
    title: "React To Do List",
    description: "A simple React-based to-do list app.",
    technologies: ["React", "CSS", "JavaScript"],
    github: null,
    demo: "https://todolist.aaronnader.com/",
    image: "assets/ToDo.png",
  },
  {
    id: 5,
    title: "FitMate - Fitness App",
    description: "Fitness tracking and planning app.",
    technologies: ["React", "Chakra UI", "JavaScript"],
    github: null,
    demo: "https://fitness.aaronnader.com/",
    image: "assets/FitMate.png",
  },
  {
    id: 6,
    title: "DayZ GTA SA-MP",
    description: "DayZ mod for GTA SA-MP multiplayer.",
    technologies: ["PAWN", "C++", "MySQL"],
    github: "https://github.com/AaronNader96/Project-DayZ-SAMP",
    demo: null,
    image: "assets/dayzPhoto.jpg",
  },
  {
    id: 7,
    title: "Zombie Command Line Game",
    description: "Text-based zombie survival game.",
    technologies: ["Python"],
    github: "https://github.com/AaronNader96/Zombie-Command-Line-script",
    demo: null,
    image: "assets/zombie.png",
  },
  {
    id: 8,
    title: "Tic Tac Toe",
    description: "Classic Tic Tac Toe game in the browser.",
    technologies: ["HTML", "CSS", "JavaScript"],
    github: null,
    demo: "http://aaronnader.com/tictactoe/",
    image: "assets/ticTac.jpg",
  },
  {
    id: 9,
    title: "aaronnader.com (this website)",
    description: "Personal portfolio website.",
    technologies: ["React", "Vite", "Chakra UI"],
    github: null,
    demo: "http://www.aaronnader.com/",
    image: "assets/portfolio.png",
  },
  {
    id: 10,
    title: "Stay True Dog Training",
    description: "Dog training business website.",
    technologies: ["React", "Vite", "Tailwind CSS"],
    github: null,
    demo: "http://staytruedog.aaronnader.com/",
    image: "assets/staytrue.png",
  },
  {
    id: 11,
    title: "Login System",
    description: "Node.js/Express/EJS login system.",
    technologies: ["JavaScript", "Node JS", "EJS"],
    github: "https://github.com/AaronNader96/Login-System-Node-JS-Express-EJS",
    demo: null,
    image: "assets/login.png",
  },
  {
    id: 12,
    title: "AI Cooking Game",
    description: "Basic AI cooking game in JavaScript.",
    technologies: ["JavaScript", "HTML"],
    github: "https://github.com/AaronNader96/AI-Basic-Cooking-Game-JS",
    demo: null,
    image: "assets/aiCooking.jpg",
  },
  {
    id: 13,
    title: "Miller Campus Cafeteria - Internship Project",
    description: "Cafeteria menu and ordering system.",
    technologies: ["JavaScript", "HTML", "PHP"],
    github: null,
    demo: "https://www.aaronnader.slccwebdev.com/internship/cafe/index.php",
    image: "assets/miller.png",
  },
];

export const timeline = [
  {
    id: 1,
    date: "2023 - Present",
    title: "Founder & Lead Developer",
    company: "Immaculate Heart Tech",
    description:
      "Founded tech company focused on creating meaningful, innovative solutions. Leading development of multiple client projects while maintaining a full time job.",
    skills: [
      "Leadership",
      "Full-Stack Development",
      "Business Strategy",
      "Client Relations",
    ],
  },
  {
    id: 2,
    date: "2023 - Present",
    title: "Full-Stack Software Engineer",
    company: "Capital One",
    description:
      "Working with a unique small team developing internal applications for reporting, agent metrics, handling support rotation, tickets, and more. Utilizing React for front-end development and Node.js for back-end services.",
    skills: [
      "React",
      "Node.js",
      "PostgreSQL",
      "Snowflake",
      "Teradata",
      "Git",
      "CI/CD Pipeline",
      "Jenkins",
      "OCP Container",
      "Express.js",
    ],
  },
];
